### ISSUE TITLE
Missing ) on line 233 of development branche

### ISSUE THREAD

**Issue by Martin-P** [mjsarfatti/nestedSortable#10]
I found an error in the latest update in the development branche. There is a ) missing on line 233 of query.mjs.nestedSortable.js.

**Current situation**:
- (pid ? (o.key && o.expression ? pid[1] : pid[2]) : o.rootID);

**New situation**:
- (pid ? (o.key && o.expression ? pid[1] : pid[2]) : o.rootID));

**Comment by mjsarfatti** [comment]
Fixed and commited, thanks!
