### ISSUE TITLE
does expandOnHover and startCollapsed work?

### ISSUE THREAD

**Issue by marcucio** [mjsarfatti/nestedSortable#101]
I see the following option in your sample code but no reference int he plugin code:

expandOnHover: 700,
startCollapsed: true

Is expandOnHover supposed to work?

Thanks

**Comment by mjsarfatti** [comment]
Of course it is :)

look at the alpha 2.0 code, and also note that the expand functionality works by switching classes, so you will have a proper css that toggles opacity, height, display or whatever.

**Comment by marcucio** [comment]
thanks I didn't see the 2.0 branch, this helps a lot
