### ISSUE TITLE
toArray: Wrong left and right values due to root node

### ISSUE THREAD

**Issue by Martin-P** [mjsarfatti/nestedSortable#11]
First of all, I really like this plugin! Great work.

There is a bug in the toArray method wich makes left and right values go wrong. This happens because the root node is counted twice in the current situation. The fix is to skip the root node and start counting with the children of the first list item.

**Current situation line 289:**
`$(this.element).children(o.items).each(function () {`

**New situation line 289:**
`$( this.element ).first( 'li' ).children('li').each(function () {`

**Comment by Martin-P** [comment]
Forget my recommended fix, I mixed up the development branche and the master branche and passed an argument to first() which is not even possible :)

Anyhow, I gave it another try and this fixes it for me (using the version from the development branche). When the option rootID is defined, it uses that option and when it is not defined it falls back to the default id given to the root element.

``` javascript
toArray: function(options) {

    var o = $.extend({}, this.options, options),
        sDepth = o.startDepthCount || 0,
        ret = [],
        left = 1;

    $(this.element).children(o.items).each(function () {
        left = _recursiveArray( this, sDepth, left);
    });

    ret = ret.sort(function(a,b){ return (a.left - b.left); });

    return ret;

    function _recursiveArray(item, depth, left) {

        var right = left + 1,
            id,
            pid;

        if ($(item).children(o.listType).children(o.items).length > 0) {
            depth ++;
            $(item).children(o.listType).children(o.items).each(function () {
                right = _recursiveArray($(this), depth, right);
            });
            depth --;
        }

        id = ($(item).attr(o.attribute || 'id')).match(o.expression || (/(.+)[-=_](.+)/));

    if (depth === sDepth) {
      pid = null;
      if (o.rootID) {
          id[2] = o.rootID;
      }
    }
        else if (o.rootID && depth === sDepth + 1) {
            pid = o.rootID;
        } else {
            var parentItem = ($(item).parent(o.listType)
                                     .parent(o.items)
                                     .attr(o.attribute || 'id'))
                                     .match(o.expression || (/(.+)[-=_](.+)/));
            pid = parentItem[2];
        }

        if (id) {
                ret.push({"item_id": id[2], "parent_id": pid, "depth": depth, "left": left, "right": right});
        }

        left = right + 1;
        return left;
    }

},
```

**Comment by mjsarfatti** [comment]
I like your fix, but the problem is, what if I want my root ID to be `null`?
What is your markup anyway? The root item is not supposed to be a real element (the way I'm thinking of it at least).

**Comment by Martin-P** [comment]
Thanks. I do not want to return the question, but I do not think there is a situation where you want the rootID to be null?

I am working on a custom made CMS and in the database I use the nested set with my pages. The markup I use is as follows:

```
<ol class="sortable">
  <li id="page-1">
    <div>Home - / [1,12]</div>
    <ol>
      <li id="page-2"><div>Blog - /blog/ [2,3]</div></li>
      <li id="page-3">
        <div>Media - /media/ [4,9]</div>
        <ol>
          <li id="page-4"><div>Audio - /media/audio/ [5,6]</div></li>
          <li id="page-5"><div>Video - /media/video/ [7,8]</div></li>
        </ol>
      </li>
      <li id="page-6"><div>Contact - /contact/ [10,11]</div></li>
    </ol>
  </li>
</ol>
```

The home page is the root node of all pages and is a real existing page and therefore a real node. As I am typing this, I realise that perhaps it is not 100% necessary that it is a real node. It could be replaced by a fictional node because the left and right values will not change when items are being moved around. In most cases however I think it is a real node. When I take a look at some pages where the nested set is explained, I see root elements that are real nodes.
For example:
http://web.archive.org/web/20110606032941/http://dev.mysql.com/tech-resources/articles/hierarchical-data.html
http://www.sitepoint.com/hierarchical-data-database-2/

When the root node is not a real node, it is impossible to collect full paths to specific children in the tree because you are always missing the root element in that case.

I am looking forward to your view on this matter :-)

**Comment by mjsarfatti** [comment]
When I designed the plugin I thought of two use cases.

**1.**
Just as in your example, a real node is the one and only parent of all the rest. No other node will ever be at root level, and the root element cannot be deleted, but it can be modified and it is visible. In this case you would assign `rootID: 1` in the options (as the Home page node would likely be the first record of the table), and make sortable only the second level list.

```
<ol>
  <li>
    <div>Home - / [1,12]</div>
    <ol class="sortable">
      <li id="page-1">
      ...
```

**2.**
There is no real root element, but a number of first level items. In this other case the root element would be a real record in the db, but it would be ignored. In a foreach loop, the element with id 'null' would be ignored (easy to check against).

```
<ol class="sortable">
  <li id="cat-1"><div>Computers</div></li>
  <li id="cat-2"><div>Cameras</div></li>
  <li id="cat-3"><div>Sound Systems</div></li>
  ...
```

(btw, I started developing the plugin while I was developing a custom CMS, structured just like yours)

**Comment by Martin-P** [comment]
I see your point and I agree that a root level is not needed in those cases, because you are only sorting.

In my case I am thinking about not only sorting the existing pages, but also creating an option to add pages (and perhaps delete pages?) using this tree overview. When I add (or delete) a page I also need the right value of the root node to be updated. That is the main reason why I use a real node and noticed this issue.

**Comment by mjsarfatti** [comment]
I think your case is n. 1.

Just use this structure (I simply changed the sortable class assignment):

```
<ol>
  <li id="page-1">
    <div>Home - / [1,12]</div>
    <ol class="sortable">
      <li id="page-2"><div>Blog - /blog/ [2,3]</div></li>
      <li id="page-3">
        <div>Media - /media/ [4,9]</div>
        <ol>
          <li id="page-4"><div>Audio - /media/audio/ [5,6]</div></li>
          <li id="page-5"><div>Video - /media/video/ [7,8]</div></li>
        </ol>
      </li>
      <li id="page-6"><div>Contact - /contact/ [10,11]</div></li>
    </ol>
  </li>
</ol>
```

Your Home, with ID 1, is not movable/deletable. If you set the option `rootID: 1`, then you would always have the right right value (no pun intended) for the first, implicit, element of the array. 

```
    '0' ...                                  // Home
        'item_id' => "1"
        'parent_id' => "none"
        'depth' => "0"
        'left' => "1"
        'right' => "12"
    '1' ...                                  // Blog
        'item_id' => "2"
        'parent_id' => "1"
        'depth' => "1"
        'left' => "2"
        'right' => "3"
    ...
```

**Comment by Martin-P** [comment]
You are totally right, I see your point now. My case is indeed the no. 1 situation. I applied this to my setup and it works like a charme. So it is not a bug and no fix is needed, but I implemented it in a different way as it was designed to be used.

Thanks for pointing this out to me and thanks for this great plugin.

**Comment by mjsarfatti** [comment]
Glad we worked it out!

**Comment by brunoandradebr** [comment]
I'm getting an error when using toArray twice. I'm using in start event and in update event. the error message is : "Can not get property 'match' of undefined reference or null".
