### ISSUE TITLE
Incompatibility with jQuery 1.10 and jQuery UI 1.11

### ISSUE THREAD

**Issue by dswbx** [mjsarfatti/nestedSortable#120]
I'm getting an error using Nested Sortable v2.0 with jQuery 1.10 and jQuery UI 1.11 at line 16:

$.widget("mjs.nestedSortable", $.extend({}, $.ui.sortable.prototype, { ... }
Error Message: Uncaught TypeError: Cannot read property 'prototype' of undefined 

And I cannot go back to jQuery UI 1.8+ because the $.browser method has been removed by jQuery 1.9. What's the problem or what changed with UI 1.11?

Thanks!

**Comment by marcucio** [comment]
Did you include jQuery ui.sortable too or just jQuery? You need both for this to work.

**Comment by dswbx** [comment]
OMG this is embarrassing now.. I was using a custom build of jquery ui and I assume there wasn't sortable included. The full version worked. 

Thank you very much und sorry :-/
