### ISSUE TITLE
Items jump up if the window is scrolled down (Please help me)

### ISSUE THREAD

**Issue by camohub** [mjsarfatti/nestedSortable#122]
Hi,
I know that I shoul ask here: https://github.com/ilikenwf/nestedSortable 
and I did it: https://github.com/ilikenwf/nestedSortable/issues/41
But it seems that I will waiting few weeks for the answer. So I must try this way. 
Please if you have a time look at this: https://github.com/ilikenwf/nestedSortable/issues/41

Can you help me?

**Comment by mjsarfatti** [comment]
Hi, I'm sorry but I don't maintain this plugin anymore, you should go to it's new home here: https://github.com/ilikenwf/nestedSortable
