### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by ebrost** [mjsarfatti/nestedSortable#123]
I use your plugin and tried the change parameter to ajax submit the list with the 'toArray' parameter . i had the following issue : "Uncaught TypeError: Cannot read property 'match' of undefined" wich can be corrected by the following

in jquery.mjs.nestedSortable v2.0), replace line 769 : id = ($(item).attr(o.attribute || "id")).match(o.expression || (/(.+)-=_/));

by: id = ($(item).attr(o.attribute || "id") ||'').match(o.expression || (/(.+)-=_/));

**Comment by mjsarfatti** [comment]
Hi, I'm sorry but I don't maintain this plugin anymore, you should go to it's new home here: https://github.com/ilikenwf/nestedSortable
