### ISSUE TITLE
Using Nested Sortable in WordPress Admin Sortable box

### ISSUE THREAD

**Issue by simonbbrown** [mjsarfatti/nestedSortable#124]
Hi,

This one is a little hard to give a working example for, but I've been working on a plugin that uses NestedSortable for WordPress.
The idea is to allow users to drop in all kids of different layouts and be able to drag them in and out of each other.
Everything is working fine, except for, when sorting, if I drag the item to far it can come out of its container.

Here is an example of how I'm instansiating NestedSortable:

`workbench.nestedSortable({
            forcePlaceholderSize: true,
            handle: '.handle',
            cancel: 'a, button, input',
            helper: 'clone',
            items: 'li',
            opacity: .6,
            placeholder: 'placeholder',
            revert: 250,
            tabSize: 25,
            tolerance: 'pointer',
            toleranceElement: '> div',
            isTree: true,
            maxLevels: 3,
            startCollapsed: false,
            isAllowed: isDropAllowed,
            relocate: removeEmptyLists
        });`

jQuery error I get:
Uncaught Error: cannot call methods on nestedSortable prior to initialization; attempted to call method 'option'

The problem seems to be, that in the WordPress interface I have my Workbench inside of a WordPress admin box, which uses the Sortable jQuery UI library, I suspect that its having a bit of fun with this and allowing my workbench elements to be dragged out of the workbench and into the sortable areas. Once an element gets dragged out of the workbench its lost to the workbench and cannot be dragged back in.

Any thoughts? I'm going to try and remove it from the sortable area to see if that helps, but would really appreciate if theres someway to say, element cannot be removed from the nestedSortable element.

**Comment by mjsarfatti** [comment]
Hi, I'm sorry but I don't maintain this plugin anymore, you should go to it's new home here: https://github.com/ilikenwf/nestedSortable
