### ISSUE TITLE
Relocate event uses element's IDs hardcoded

### ISSUE THREAD

**Issue by lllopo** [mjsarfatti/nestedSortable#125]
The 'relocate' event matches elements using their ID attribute :

`this._pid_current === this._uiHash().item.parent().parent().attr("id")`

while the attribute might be different, for example 'data-id' (see toArray method). So if we have a setup where entries IDs are in other html attribute and not in the ID attribute, 'relocate' does not function properly (like doesn't fire when the first element of a branch is moved) as the _pid_current is always undefined.

**Comment by mjsarfatti** [comment]
Hi, I'm sorry but I don't maintain this plugin anymore, you should go to it's new home here: https://github.com/ilikenwf/nestedSortable

**Comment by lllopo** [comment]
Yes, sorry, my fault. Thanks anyway.
