### ISSUE TITLE
How change default rendering of plugin? How to take current information about node after drag and drop?

### ISSUE THREAD

**Issue by nurzhannogerbek** [mjsarfatti/nestedSortable#129]
First of all thanks for this plugin! :)

I have some questions.

1) I have tree with next structure:

```
<ol id="documents" class="list-group">
    <li class="list-group-item"> <!-- B -->
        <div>Some content</div>
    </li>

    <li class="list-group-item">
        <div>Some content</div>
        <ol class="list-group">
            <li class="list-group-item"> <!-- A -->
                <div>Some content</div>
            </li>
            <li class="list-group-item">
                <div>Some content</div>
            </li>
        </ol>
    </li>
</ol>
```

When I remove node A and want to make it child of element B  by default nestedSortable plugin put `<ol>`. I need to put `<ol class="list-group">`. Is it possible to change this default behavior?!

2) Is it possible to take JSON with current information about node after drag and drop? Lets say information like: `position`, `level`, `parent_id` of nodes? Can you show me example if it possible, please? :)

**Comment by mjsarfatti** [comment]
Hi, unfortunately I’m not the maintainer of the project anymore.
nestedSortable is currently maintained at ilikenwf/nestedSortable, you should have a look there :)
