### ISSUE TITLE
restrict the child moving to other parent and only change the child positions

### ISSUE THREAD

**Issue by rubian** [mjsarfatti/nestedSortable#16]
Hi

I have three questions
How can i restrict child moving to other parent .
Should  only drag and drop in their nest just for position change .
The child should restrict to become root or parent.

**Comment by mjsarfatti** [comment]
Hi, this is not a support forum. Please visit http://mjsarfatti.com/sandbox/nestedSortable/forum/ to get an answer to your questions.
