### ISSUE TITLE
Using <ul> crashes Google Chrome

### ISSUE THREAD

**Issue by raphaelm** [mjsarfatti/nestedSortable#19]
As soon as I try to use your plugin for an <ul> element instead of an <ol> element (which works perfectly fine with standard jQuery UI sortable()) Chrome freezes. I don't think that's intended and should be at least documented

**Comment by mjsarfatti** [comment]
Hi,
i'm sorry this issue still causes trouble. It's documented that you have to specify the kind of list you are using, and if you use the develop branch the browser won't crash any more.

**Comment by raphaelm** [comment]
Uh, just saw that stackoverflow has problems with my markup :D Okay, in this case I assume I just did not see the point in the documentation. Besides, thank you for the great plugin!
