### ISSUE TITLE
Maxlevels issue

### ISSUE THREAD

**Issue by ilyakar** [mjsarfatti/nestedSortable#27]
Hi.
When I Maxlevels to 2, everything is fine as long as i'm dragging an element to a parent which currently doesn't have any submenu. When i try to add another submenu to that one, it doesn't allow it. So far so good!
 On page reload, it DOES allow a submenu (third maxlevel) on that submenu. I take it this is a bug.

Would be nice if this would be fixed.

Greets.

**Comment by mjsarfatti** [comment]
The plugin does not (and should not) check on the html you send to the browser and modify it according to its will. If that's wht you mean...
