### ISSUE TITLE
toArray and toHierarchy

### ISSUE THREAD

**Issue by lasterra** [mjsarfatti/nestedSortable#28]
Both methods look for 'li' as a childrens of options.listType instead of options.items

**Comment by michael-martin** [comment]
That's fixed in the development version: https://github.com/mjsarfatti/nestedSortable/blob/develop/jquery.mjs.nestedSortable.js

**Comment by lasterra** [comment]
Ok, i will try dev version.

Thanks

2012/5/31 Michael Martin <
reply@reply.github.com

> That's fixed in the development version:
> https://github.com/mjsarfatti/nestedSortable/blob/develop/jquery.mjs.nestedSortable.js
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mjsarfatti/nestedSortable/issues/28#issuecomment-6033388

## 

---

Enrique Rodriguez Lasterra
lasterra AT javahispano DOT org
http://www.javahispano.org
Asociación sin ánimo de lucro sobre java
Spanish non profit association about java
