### ISSUE TITLE
Prepopulation error

### ISSUE THREAD

**Issue by facelesslucifer** [mjsarfatti/nestedSortable#31]
This plugin is not work on pre population data. I am passing the HTML format from PHP and take the jQuery for pre population.

**Comment by mjsarfatti** [comment]
Can you post a jsbin/jsfiddle example? I don't understand what the problem is...

**Comment by facelesslucifer** [comment]
Now, I solved that problem. It's not your jQuery problem. Sorry about that. Thank mjsarfatti
