### ISSUE TITLE
How to expand nodes using AJAX?

### ISSUE THREAD

**Issue by henrydjacob** [mjsarfatti/nestedSortable#36]
We have large tree, like to expand nodes on click on a icon, is it possible to implement this?

**Comment by mjsarfatti** [comment]
Hi,
this function is currently under development, please check back in a week or so.

**Comment by henrydjacob** [comment]
Any update on the AJAX feature?

**Comment by mjsarfatti** [comment]
Hi,
I'm currently developing the feature for a small company that requested it. They will let me make it public as soon as it is finished. I'm waiting for a response on the latest version from them. Sorry to make you wait!

**Comment by dryaf** [comment]
Any update on the AJAX feature? :-)

**Comment by mjsarfatti** [comment]
the alpha2.0 branch let's you do it
