### ISSUE TITLE
I have already implemented nestedSortable,Now i want to customise it,is it possible? 

### ISSUE THREAD

**Issue by MilindS** [mjsarfatti/nestedSortable#37]
i want my customization in such a way that in my view if i have my tree structure of only Top level nodes and if i click on any of the top level node then it should be expanded which would be having all of its child and sub-child nodes.please advice.....

**Comment by ryfeng** [comment]
Identical to issue #36

You don't need to do anything with nestedSortable.

Initially render the inner lists (`<ol>` or `<ul>`) as `display: none;`
Put the following code in the same function as your `$.nestedSortable()` call

Show all children

```
$(containerSelector).on('click', selectorForListElements, function() {
    $(this).find(listSelector).show();
});
```

Show only the next-in-line children

```
$(containerSelector).on('click', selectorForListElements, function() {
    $(this).children(listSelector).show();
});
```

From your description, it seems you'd want the first option.
