### ISSUE TITLE
protectRoot doesnt work when moving fast repeatedly

### ISSUE THREAD

**Issue by SirCumz** [mjsarfatti/nestedSortable#38]
When this option is enabled and i try to move the same root node again fast while still being moved it parses the root node to a sub item!

Try to move a rootnode to a sub and try to do it fast again while the root node is going back to its root position

**Comment by mjsarfatti** [comment]
Thanks, this is being addressed in version 2.0

**Comment by mjsarfatti** [comment]
fixed.
