### ISSUE TITLE
isAllowed arguments should contain "currentItem" and "item" should be renamed "placeholder"

### ISSUE THREAD

**Issue by nreynis** [mjsarfatti/nestedSortable#40]
"isAllowed" method just have access to the "parentItem" (the drop target) and the misleadingly nammed "item" which in fact is not the item being dropped, but the placeholder.

This limit greatly the usefullness of this method...
Static constraints can already be declared  using "disableNesting" and "maxLevels", therefore the real use of "isAllowed" is expressing dynamic, context-dependant constraints.
By providing only the placeholder and the parent node you give user a small part of the context (the drop position in a given childList) which (IMHO) is of little help. By also providing "currentItem" the user could write constraints depending on the nature of the item being dropped, ex :
Leaf node of type A can only be appended to node of type B and D

**Comment by AlterHaudegen** [comment]
Temporary workaround: As soon as the placeholder is deactivated "item" acts as expected. I'll do that for now, but it would be really nice to have both.

**Comment by mjsarfatti** [comment]
Working on it!
