### ISSUE TITLE
Placeholder not visible

### ISSUE THREAD

**Issue by almaron** [mjsarfatti/nestedSortable#41]
Using: jQuery 1.7.2, jQuery UI 1.8.18, jQuery Nested Sortable 1.3.5.
Can't customize the look of a placeholder to drop the item/
It seems that its behavior has been changed. Now it gives markup like this:

``` html
 <li class="ui-sortable-placeholder" style="visibility:hidden; height:24px;" >
```

So even if I use that class in the css, it would not show up.
There must be some way to overcome it.

**Comment by almaron** [comment]
Found the problem. Will make a pull request with the cure.

**Comment by trullock** [comment]
What was the problem? this comment thread is the top google result for the same problem im having with normal ui sortable. tahnks

**Comment by kevinknelson** [comment]
closed 10 months ago...hmm...I don't see a pull-request, and this was still an issue for me.  So, in the event someone else hits this page...After "var previousTopOffset = this.placeholder.offset().top", I added this line, which seems to work fine so far:

this.placeholder.css('visibility','visible');

**Comment by JonoB** [comment]
@kevinknelson Thanks, fixed it for me
