### ISSUE TITLE
HTML5 instead of jquery ui

### ISSUE THREAD

**Issue by lukasoppermann** [mjsarfatti/nestedSortable#43]
Hey,

jquery ui seems to be quite a huge load and it often has errors. I do not know if this is possible, but maybe the nestedSortable could be ported to html5?

**Comment by BoringCode** [comment]
Um, do you even know what HTML5 means?

**Comment by lukasoppermann** [comment]
Uh, yes. Why? Html5 has a drag and drop api, which is enough to build sortable lists like this one. https://github.com/farhadi/html5sortable so there is a good chance jquery ui could be dropped in favor of html5 dnd IF a nested sortables are possible (which I do not know, which is why I asked). So I do not really get what your problem is.

**Comment by BoringCode** [comment]
Okay, sorry for being a bit blunt :)

The HTML5 drag and drop API refers to being able to drag and drop files onto the web browser, it doesn't apply here.

**Comment by lukasoppermann** [comment]
So how come there is a html5sortable js lib using this API?

**Comment by mjsarfatti** [comment]
I had a look at the plugin you linked to, and it makes sense. It could definitely be ported to that. I just don't have time at the moment :)

**Comment by lukasoppermann** [comment]
Awesome, so you think the nested list situation would not make it impossible? If you ever have time for it, that would be awesome, because jquery ui is quite a huge thing to load, if it is just for sortables.

**Comment by mjsarfatti** [comment]
I know it's big, but it's not much if compared to, say, a picture! Anyway,
maybe one day... But I can't make any promise for the moment.

2012/8/17 Lukas Oppermann notifications@github.com

**Comment by lukasoppermann** [comment]
Well, maybe you can just tag it as a feature request, and if you ever get the time to do it, great. Cheers, keep up the good work anyway.

**Comment by durasj** [comment]
+1
