### ISSUE TITLE
widget failed on IE for jQuery-ui-1.8.2?

### ISSUE THREAD

**Issue by RomeoQNgo** [mjsarfatti/nestedSortable#44]
This is amazing btw.  it works great.
Not sure if it is only me or not but it fails on IE (I use 9 for this test) when combine with jQuery-ui-1.8.2, works for everything in firefox and chrome.  maybe it is an IE issue.  when I change the UI to 1.8.11, it works on UI.
Thank you very much for this.  I really appreciate it.

**Comment by mjsarfatti** [comment]
Hi,
it's very strange, nothing much changed. Does the regular Sortable work? If not, it's their problem :) Otherwise can you give some more detail on the problem? Any javascript error?

Thank you
