### ISSUE TITLE
How to use isAllowed function?

### ISSUE THREAD

**Issue by damour** [mjsarfatti/nestedSortable#45]
isAllowed: function(item, parent)
        {
            alert('disableNesting');
            return true;
        }

**Comment by lsdevries** [comment]
'item' is the item you drag, 'parent' is the item you drop on.
try using console.log(item, parent) to see whats happens.

In a folder/file tree where nothing should be dropped on files, I use:

```
isAllowed: function(item, parent)
{
    // returns true if li's classname not is 'File'
    return (parent != null && parent.attr('class') != 'File')
}
```
