### ISSUE TITLE
draggable list - locking child nodes in template

### ISSUE THREAD

**Issue by mcnejef** [mjsarfatti/nestedSortable#48]
I'm using nestedSortable for a simple workflow designer.  We have a draggable list of items that serve as templates for types of workflow steps.  One workflow step is a boolean branch (do this if true, do that if false).  My draggable template looks like the following:

```
    <li class="ui-state-highlight draggable blue no-nest">
        <div class="title">
            Boolean
            <div class="button" onclick="$(this).parent().parent().remove();">X</div>
        </div>
        <ol class="cases">
            <li class="ltblue"><div class="title">True</div><ol></ol></li>
            <li class="ltblue"><div class="title">False</div><ol></ol></li>
        </ol>
    </li>
```

The addition of the "no-nest" class on the LI tag keeps other steps from being added at the same level as the True and False templates when one is pulled into the sortable list.  However, the True and False nodes are themselves still sortable...meaning I can pull the entire True structure out to a different level where it breaks my workflow rules (each Boolean step must have a True and a False child).

Any idea how I can lock those children in place, like through the use of a CSS class?  Something like "no-move"?

BTW, this is one of the coolest, simplest jQuery projects I've ever seen...love it!

**Comment by mjsarfatti** [comment]
You should exclude those `li`'s from the options.
Say you give your sortable `li`'s a class, like **sortable-li**, in the options you would specify:

```
items: 'li.sortable-li'
```

**Comment by mcnejef** [comment]
Excellent, thank you!

**Comment by mcnejef** [comment]
Actually, may have closed that prematurely...

I still want to be able to sort another item underneath those "True" and "False" LI's.  Strangely, it'll let me do that with the "False" LI (bottom of the two) but not the "True" LI (top of the two).  I'm not getting an active drop location between the two locked (non sortable-li) items.  I could send a screenshot if that would be helpful.  Here's what my options look like:
        $('ol.sortable').nestedSortable({
            disableNesting: 'no-nest',
            forcePlaceholderSize: true,
            handle: 'div',
            helper: 'clone',
            maxLevels: 10,
            opacity: .6,
            placeholder: 'placeholder',
            revert: 250,
            tabSize: 25,
            tolerance: 'pointer',
            toleranceElement: '> div',
            items: 'li.can-sort'
        });

**Comment by mjsarfatti** [comment]
yes, a screenshot would be helpful :)
why do you want to place an item in between those T and F in the first
place?

2012/9/6 mcnejef notifications@github.com

**Comment by mcnejef** [comment]
Trying to reply through email with an attached screenshot...we'll see if
this works.

I want to be able to nest a child under "True", but not allow placement
between "True" and "False" as a peer.  Hopefully the screenshot will give
you an idea of the purpose, too.

Thanks for your help!

**Comment by mcnejef** [comment]
well, didn't accept the email image attachment...try this:

https://www.dropbox.com/s/yrozmygylr8ts3j/Screen%20Shot%202012-09-06%20at%2010.53.07%20AM.png?%20m

**Comment by mjsarfatti** [comment]
Ok I see. I think it would be simpler to use different Sortables instead of one huge nestedSortable.
One for the **Steps**, and others for each single outcome (True, False, etc.)

**Comment by mcnejef** [comment]
I can understand why your solution would work, but I'm confused as how I'd go about implementing it.  Here's something I just did that seems to work:

```
        $("ol.sortable").bind("sortstop", function (event, ui) {
            return ui.item.hasClass("can-sort");
        });
```

It does what I want as far as not allowing those true / false containers to be moved, and I can still add children.  The only side effect is that you can still drag it around, with the appearance that it's going to work and you don't know there is a restriction until you let go of the mouse and it returns to its original position.  I tried to move the logic into the "sortstart" event, but it ended up removing the block altogether.  I'd have to learn more about the native sortable's stuff to fully understand it.

I'm not sure if you would see value in it, but it'd be cool if you could configure nestedSortable with selectors/classes for items that:
- do not allow children (already there with 'disableNesting')
- are not allowed to be moved (my problem, something like 'disableMoving')
- cannot be at the top-most level ('disableRoot')

Again, though, nestedSortable is super cool.  Saved me so much time and effort.  I'll see if I can find some pizza money for you.

**Comment by mjsarfatti** [comment]
Added to the feature request!
Another thing came to my mind just now: why don't you use the `handle` option?
With a code like this:

```
<li class="ui-state-highlight draggable blue no-nest">
    <div class="handle title">
        Boolean
        <div class="button" onclick="$(this).parent().parent().remove();">X</div>
    </div>
    <ol class="cases">
        <li class="ltblue"><div class="title">True</div><ol></ol></li>
        <li class="ltblue"><div class="title">False</div><ol></ol></li>
    </ol>
</li>
```

And the option:

```
handle: 'div.handle'
```

You wouldn't be able to "pick up" the T/F elements. You could still keep your sortstop function as an added security, but it's probably not needed.

**Comment by Spiderkeg** [comment]
Very easy fix for this, it's actually in the official documentation.

items: 'li:not(.ui-state-disabled)'

Place " items: 'li:not(.ui-state-disabled)' " in your options (minus the quotations) and this should solve your problems.  The sub-items children should remain movable.  The parents (if given the class ui-state-disabled) will be unmovable.  Any class could be used, per sé.

Similar to a post above.  This may prevent adding sub-items to root items that don't have sub-items upon page load/activation.

**Comment by Spiderkeg** [comment]
Another option:

```
        stop: function(event, ui) {
            if (ui.item.hasClass("root")) {
                $("ol.sortable").sortable("cancel");
            }
        }
```

Place this among the options.  When a user attempts to drag one of the root items, the item will resume it's original position.  Just remember to apply the "root" class to the root items (or whatever class you want).  While this doesn't prevent a user from being able to drag the item, the item won't stick to a new location.

Similar to a post above, but this is in keeping with Events already provided by Sortable.

**Comment by rvanswaay** [comment]
Problem with the solutions above is they don't allow the element to be moved at all.
If you want to move an element up and down the list, but not allow it to move inside other elements / keep it on the root level, (yet allow other elements to nest inside it) you can go to the handle for example, and do this:
&lt;span class="handle" onMouseDown="
$('.sortable').nestedSortable('option', 'maxLevels', 1);
$('.sortable').nestedSortable('option', 'tabSize', 9999);
"&gt;drag me&lt;/span&gt;
... for elements that can move above the root level, do this:
&lt;span class="handle" onMouseDown="
$('.sortable').nestedSortable('option', 'maxLevels', 0);
$('.sortable').nestedSortable('option', 'tabSize', 20);
"&gt;drag me&lt;/span&gt;

**Comment by ghost** [comment]
I know this is old but I have a similar question. I have items in the list that I want to disable when they are in the correct position. This works. By that I mean that I cannot move them when trying to drag them. However when I place another item over them, they swap their place with that item. So how do you lock items in place so that they will not move anymore even when placing an item over them, similar to having them fixed at start. basically I want them to be fixed when they reach the correct position I want them in. Does not make sense?

**Comment by mjsarfatti** [comment]
Hi, unfortunately I’m not the maintainer of the project anymore.
nestedSortable is currently maintained at https://github.com/ilikenwf/nestedSortable, I recommend you have a look there :)

**Comment by ghost** [comment]
Thanks!
