### ISSUE TITLE
Keep in container list

### ISSUE THREAD

**Issue by justindasilva** [mjsarfatti/nestedSortable#49]
Looking at the example on http://mjsarfatti.com/sandbox/nestedSortable/

Basically, I would like to constrain the subitems to only be orderable within their parent item.
So in the example, "Sub Item 1.1" and "Sub Item 1.2" can only be interchanged, but cannot be placed anywhere else.

I was trying to make use of the isAllowed function, but apparently this plugin strips away data tags from the li element. (I added data-parent attributes.)

**Comment by mjsarfatti** [comment]
Yes, in fact the 'item' is the placeholder, not the original <li> element.
For your situation I would suggest you use different connected sortables
instead.

2012/9/4 medj notifications@github.com

**Comment by gihrig** [comment]
Dude, this SugarSync thing is getting kinda spammy!

**Comment by mjsarfatti** [comment]
Ouch, the github issue email reply must have slipped in the addresses I've sent the invitation too... :\
