### ISSUE TITLE
Detect the listType from element, avoid browser freeze

### ISSUE THREAD

**Issue by Ciantic** [mjsarfatti/nestedSortable#5]
Hi!

I spent last hour wondering why the hell it doesn't work, my browser (Chrome beta) freezed literally. And the reason? Default list type is `ol` not `ul`. If I try to use `$("ul.sortable").nestedSortable` it just freezed.

Ways to fix this:
1. _Detect_ the listType from the parent element using nodeName, e.g. `jQuery("<ul></ul>").get(0).nodeName`...
2. Throw error and don't freeze the browser.

**Comment by mjsarfatti** [comment]
Yes, the default list type is `ol`, and it's written in the docs in different places.
Anyway it's a good idea to autodetect the list type, I will see what can be done.

**Comment by Ciantic** [comment]
Found it from the docs, anyhow freezing is not a good default.

I must correct that according to http://reference.sitepoint.com/javascript/Node/nodeName one should use `jQuery("<ul></ul>").get(0).nodeName.toLowerCase()` for best support...

**Comment by mjsarfatti** [comment]
fixed
