### ISSUE TITLE
Code breaks when option 'scroll' is set to false (patch included)

### ISSUE THREAD

**Issue by nreynis** [mjsarfatti/nestedSortable#51]
When setting the 'scroll' option to false, _mouseDrag fails because of scope issue. The fix is quite simple, just set the value for 'o' variable one block higher :

l54 :

``` javascript
}

var o = this.options; // <- this should be here

//Do scrolling
if(this.options.scroll) {
    var scrolled = false;
```

**Comment by mjsarfatti** [comment]
Thanks, it's fixed now!
