### ISSUE TITLE
Empty OL / UL are not being cleared

### ISSUE THREAD

**Issue by FKobus** [mjsarfatti/nestedSortable#53]
Empty OL /UL lists are not cleared after a movement.

After futher investigation it seems that the actual moving element is still in that OL/UL, along with his helper.

I'm using:
jquery 1.8.1 (google cdn)
jquery ui 1.8.23 (google cdn)

It happens at least in Firefox (10.x) and Chrome (22.x)
It seems to me that the _clearEmpty function is not working properly. 

When you add :
     if (emptyList.length && !emptyList.children().length) {
            emptyList.remove();
     } else { 
           console.log(emptyList);
     }
// EXAMPLE OUTPUT
[&lt;ol&gt;&lt;/ol&gt;]
It will print an empty &lt;ol&gt;&lt;/ol&gt;

When using 
    if (emptyList.length && !emptyList.children().length) {
        emptyList.remove();
    } else {
        console.log(emptyList.html());
    }

// EXAMPLE OUTPUT:
&lt;li id="list_10" style="display: none; "&gt;&lt;div class="node"&gt;Item 5&lt;/div&gt;&lt;/li&gt;&lt;li id="list_10" style="display: list-item; width: 200px; height: 22px; position: absolute; opacity: 0.6; z-index: 1000; left: -13px; top: -2px; " class="ui-sortable-helper"&gt;&lt;div class="node"&gt;Item 5&lt;/div&gt;&lt;/li&gt; 

It prints the old item in it's old place with its helper.

I tried several things to let the empty lists being removed.

The only solution this far was copying the whole _clear function from the ui.sortable and add at the end :

```
// Clean last empty ul/ol
for (var i = this.items.length - 1; i >= 0; i--) {
    var item = this.items[i].item[0];
    this._clearEmpty(item);
}
```

But I think this is not the way to do it.

Greetings

**Comment by FKobus** [comment]
Just realised it's contents need to be cleared by the _clear function of the sortable.
It is cleared the next time.
I needed to check the contents of the ol for my own extensions.

I rebuild the _mouseStop function with a check on id comparison if the ol is empty or not. (filtering the helpers and other handles)

**Comment by mjsarfatti** [comment]
Yep,
because of the way regular Sortable works, the original element remains hidden in its original position until the drag is over. The empty lists will be completely cleared only after the drag.
