### ISSUE TITLE
Using nestedSortable

### ISSUE THREAD

**Issue by David97** [mjsarfatti/nestedSortable#54]
Hello,

Sorry, I cannot understand what is the meaning of left and right in the following codes:-

setName[n] =>
{
    'item_id': itemId,
    'parent_id': parentId,
    'depth': depth,
    'left': left,
    'right': right,
}

what do they want? Thanks!

**Comment by nreynis** [comment]
Left and right are previous and next sibling subtrees.

They are useful if you need to do a breadth-first traversal.

**Comment by FKobus** [comment]
The left and right are not the previous and next, but a hierarchical structure:

http://www.sitepoint.com/hierarchical-data-database-2/

You can use these values for examples storing it in a database.

**Comment by nreynis** [comment]
My bad, didn't knew that. Thanks for the link !
