### ISSUE TITLE
Output containing more parameters

### ISSUE THREAD

**Issue by David97** [mjsarfatti/nestedSortable#55]
Hi,

I can implement nestedSortable in my php webpage, and I understand that there are 3 ways being serialize, toArray and toHierarchy for outputing the structure data.

Actually, I would like to include more parameters like text field and status to the output, is it possible for me to modify any one type of above to achieve the task? Thanks!

**Comment by mjsarfatti** [comment]
Hi,
At the moment you will have to stick with those, or create your serialize function. The easiest would be to modify the toArray function I guess.

Manuele
