### ISSUE TITLE
Integer as ID attribute breaks

### ISSUE THREAD

**Issue by yolandavdvegt** [mjsarfatti/nestedSortable#58]
I don't know if this is an limitation of html and integers as id's attribute. 

The problem is when I set the id attribute as id="2" in html, It returns the error:

`Uncaught TypeError: Cannot read property '2' of null`

Workaround was to prefix it with some text just like in the example.

**Comment by mjsarfatti** [comment]
I don't think you can use a pure number as ID.

2012/10/24 Woutvdvegt notifications@github.com

**Comment by FKobus** [comment]
Indeed, the id attribute cannot be just a numeric value: http://www.w3schools.com/tags/att_global_id.asp
See attribute values.
Its default html functionality what jquery doesn't breaks up/fixes

**Comment by facultymatt** [comment]
Just ran into this problem, oddly if you prefix a numeric id with a string, the toArray and toHierarchy methods truncate the id's to be a number. Not sure why this is. 

For example, id="num_1" id="num_2", etc. will translate to id:1, id:2, etc. when using the above mentioned methods. 

Any thoughts?

**Comment by mjsarfatti** [comment]
This is the default Sortable behavior :)
