### ISSUE TITLE
Empty placeholder not cleared/remove after drop and not draggable anymore

### ISSUE THREAD

**Issue by srad** [mjsarfatti/nestedSortable#59]
Dragging a item accross rows adds follow code between the rows:

```
<li class="item ui-sortable-placeholder" style="visibility: hidden; "></li>
```

But it doesn't move them after a drop and the list is not draggable after that anymore at all.

This seems to occur when you cross to a sublist.

Please see the short attached video showing this issue:

http://screencast-o-matic.com/watch/cl6ZbjSuO

**Comment by mjsarfatti** [comment]
Hi,
it has never occured before, it must have something to do with your
specific configuration, or some conflicting javascript.

2012/10/24 Saman notifications@github.com

**Comment by srad** [comment]
Issue solved, was my fault, due to faulty html.
