### ISSUE TITLE
sortchanged event does not work

### ISSUE THREAD

**Issue by Ciantic** [mjsarfatti/nestedSortable#6]
Noticed that `sortchanged` event does not work as expected, it is not fired when subelement order changes.

I propose you to propagate subtree's sortchanged event using $.trigger to the outermost sortable.

As a workaround my ajax plugin saves the ordering on `sortstop`, it just a bit hackish as the saving must be done even when no changes is done.

**Comment by mjsarfatti** [comment]
Thanks for the note, I will fix it shortly.

Many use the `update` event to save the new order (it is fired only when the DOM changes, and not if the element is dragged to a not allowed position and sent back to its original position).

**Comment by Ciantic** [comment]
Uhh, `sortupdate` works for me just fine. Now wondering what is the difference of `sortchanged` and `sortupdate`? This is exactly what I was after, and I though `sortchanged` is meant for it it didn't come to my mind there is another event.

Maybe the sortchanged is needed on cases when there is multiple droppable elements or something?

**Update:** Difference of course is semantics. `sortupdate` is triggered even when I change the DOM some otherway, and `sortchanged` is not dependant on DOM.
