### ISSUE TITLE
Error on initialize

### ISSUE THREAD

**Issue by almaron** [mjsarfatti/nestedSortable#60]
Here is the js https://gist.github.com/4001049
Here is the html https://gist.github.com/4001070
The js is loaded in the folowing sequence:
jquery.js v.1.8.2
jquery-ui.js  v.1.8.23
jquery.nestedSortable.js v.2.0
pages.js

The error is: 
Error: cannot call methods on nestedSortable prior to initialization; attempted to call method 'option'

The error is triggered when I try to drag an item.

**Comment by almaron** [comment]
Issue solved by updating the jquery-ui directly from the devs site.

**Comment by FKobus** [comment]
This error is again possible using the newest UI (1.10.3) version and Jquery (1.10.1).
I fixed it by changing:

`maxLevels = this.placeholder.closest('.ui-sortable').nestedSortable('option', 'maxLevels'); // this takes into account the maxLevels set to the recipient list`
INTO
`maxLevels = o.maxLevels`

Seems to fixes the problem.
