### ISSUE TITLE
jQueryUI 1.9.1 problem

### ISSUE THREAD

**Issue by Mangatt** [mjsarfatti/nestedSortable#62]
Hello,
I've just tryed nestedSortable with jQueryUI 1.9.1 and it has some problems, shivering is much worse than in 1.9.0, sometimes there is even imposible to move some items inside some nodes. Can someone check compatibility with 1.9.1?

http://jqueryui.com/changelog/1.9.1/

**Comment by mjsarfatti** [comment]
jQueryUI 1.9 is quite a big change, and nestedSortable has been having problems with it since the alpha releases. I think the plugin will have to be revisited (rewritten?) in depth to work with 1.9. For the moment we have to stick with 1.8...

Version 2.0 will eventually work only with 1.9 I guess.

**Comment by Mangatt** [comment]
That will be great, is there some time frame for 2.0 release? For other scripts on my page is 1.9.1 necessary, so I hope for quick solution.

**Comment by mjsarfatti** [comment]
Unfortunately not... I'm doing this in my free time and it's never enough

2012/11/16 Mangatt notifications@github.com

**Comment by Mangatt** [comment]
Any updates on that issue? Is it possible to merge NestedSortable with legacy JqueryUI sortable that works - I mean that I will be able to use new JqueryUI sortable 1.9+ in our apllication but NestedSortable will use older version of sortable? (JqueryUI 1.9+ is requirement for our application so I am trying to find a way that works) Thanks

**Comment by mjsarfatti** [comment]
Hello,
no updates unfortunately, and at this point I don't know when I will be
able to work on that. Too much work and deadlines in this period. If
somebody wants to fork the project and make it compatible with UI1.9 he/she
is most welcome!

2012/12/27 Mangatt notifications@github.com

**Comment by Mangatt** [comment]
Ok, as far as I was able to trace mentioned problem, there is issue at line 269:

this._contactContainers(event);

Placeholder is correcly appended to correct node (line 254 or 259) but line 269 will revert state. So if I want to create new node with UI 1.9.1+, I have drag mouse to right half and then is node created.

**Comment by Mangatt** [comment]
Ok, I made a quick fix for this issue. It just uses non-problematic 1.9.0 method instead rewritten method from 1.9.1. You can grab it here:

https://github.com/Mangatt/nestedSortable/blob/master/jquery.mjs.nestedSortable.compatible

**Comment by mjsarfatti** [comment]
Thank you Mangatt for now! Hope to be able to get to work on that soon.

2013/1/17 Mangatt notifications@github.com

**Comment by mjsarfatti** [comment]
fixed. nestedSortable works with 1.10.
