### ISSUE TITLE
Incompatible with touch

### ISSUE THREAD

**Issue by dereklucas** [mjsarfatti/nestedSortable#63]
Jquery sortable works on iOS and other touch platforms when paired with TouchPunch, but this doesn't. Any leads?

**Comment by mjsarfatti** [comment]
Hello,
sorry for replying so late.
The demo page includes TouchPunch. It works on my android... can you
confirm it doesn't work on iOS?

2012/11/21 Derek Lucas notifications@github.com

**Comment by vaibhavarora14** [comment]
HI @mjsarfatti ,

I am struggling with making nestedSortable responsive, but it's not working in android/iOS mobiles. It's not even working with help of touchpunch.js.

**Comment by mjsarfatti** [comment]
Hi, unfortunately I'm not the maintainer of the project anymore.
nestedSortable is currently maintained at ilikenwf/nestedSortable, you should have a look there :)
