### ISSUE TITLE
conflict with jquery UI

### ISSUE THREAD

**Issue by ndemoreau** [mjsarfatti/nestedSortable#64]
Hi,

after upgrading to jquery-ui 1.9.2, I get this message when trying to load nestedsortable:

$.widget.extend is not a function

I've googled a bit about it and it seems like this message happens when UI has been loaded twice but I don't see a double load and the problem only occurs with nestedsortable.

Can you help me to solve it?

Thanks!

**Comment by mjsarfatti** [comment]
Hi,
can you include a jsbin or something that reproduces your problem?
nestedSortable has not been tested with UI 1.9 though, and many users have
reported problems. It will probably take a rewrite to make it work, but I
don't know how soon this can happen, I'm overloaded with work at the moment
:\
If anybody wants to give it a try.....

2012/12/4 ndemoreau notifications@github.com

**Comment by mjsarfatti** [comment]
tested with UI 1.10.
