### ISSUE TITLE
connectWith option works but makes the first level elements that don't have a child, to reject nested elements.

### ISSUE THREAD

**Issue by goncalvesjoao** [mjsarfatti/nestedSortable#66]
**Hi mjsarfatti, first of all great work! Thanks.**

Now the issue:
I've used the option (connectWith: ".connectedSortable") that enables two sortable lists to share sortable elements, according to: [jQuery UI Doc](http://jqueryui.com/sortable/#connect-lists).

The code that I used was:

``` html
<ol id="sortable1" class="connectedSortable">
  <li><div>sortable1 1</div></li>
  <li>
    <div>sortable1 2</div>
    <ol>
      <li><div>sortable1 2.1</div></li>
      <li><div>sortable1 2.2</div></li>
    </ol>
  </li>
  <li><div>sortable1 3</div></li>
</ol>

<ol id="sortable2" class="connectedSortable">
  <li><div>sortable2 1</div></li>
  <li>
    <div>sortable2 2</div>
    <ol>
      <li><div>sortable2 2.1</div></li>
      <li><div>sortable2 2.2</div></li>
    </ol>
  </li>
  <li><div>sortable2 3</div></li>
</ol>

<script>
  $(document).ready(function(){
    $('#sortable1, #sortable2').nestedSortable({
      handle: 'div',
      items: 'li',
      toleranceElement: '> div',
      maxLevels: 2,
      connectWith: ".connectedSortable"
    });
  });
</script>
```

The thing is.
Elements that already have children ("sortable1 2" and "sortable2 2") work fine, but the ones that didn't have a child in the first place ("sortable1 1", "sortable1 3", "sortable2 1", "sortable2 3"), don't accept new ones.

I can see that by dragging an element hover these elements ("sortable1 1", "sortable1 3", "sortable2 1", "sortable2 3") that the `<ol></ol>` that should contain the child elements is being created, but with no content in it and when I drop the element, the `<ol></ol>` disappears.

Can you help me with this Manuele?
Thanks again, and keep up the good work :D
John.

**Comment by piotrpilz** [comment]
Got the same issue here. I solved this by adding dummy (invisible by height:0; border: 0 etc. ) element to an empty child list.

**Comment by mjsarfatti** [comment]
Thanks for the bug report, will look into that!
In the meantime please use doedoe's workaround.

2012/12/24 doedoe notifications@github.com

**Comment by goncalvesjoao** [comment]
I haven't tested the doedoe approach but I bet it works, thanks doedoe and thank you mjsarfatti for looking into it.

**Comment by nezoomie** [comment]
+1 having the same issue

**Comment by tonyennis145** [comment]
Same issue here. doedoe's solution doesn't entirely work: when the the dummy element is moved it disables the parent from accepting children again.

**Comment by piotrpilz** [comment]
@tonyennis145 : make this dummy invisible and undraggable. 
Here is my example:
`<li class="dummy" style="height: 0px; border: 0px; padding: 0px; margin: 0px;" data-id="0"></li>`

**Comment by tonyennis145** [comment]
@doedoe thanks for response, still no luck though. Could you post your full code including js?

**Comment by piotrpilz** [comment]
@tonyennis145 take a look at item "sortable2 1"
http://jsfiddle.net/DuUKS/4/

I've added a dummy child same as other children, but invisible for user.  Also an ol container has some min-height for a drop target.

Try to move a dummy element when it's zero height ;)

**Comment by goncalvesjoao** [comment]
Forgot this issue existed, going to close it.
