### ISSUE TITLE
toArray return one more 'Unnecessary' object (a wrapper)

### ISSUE THREAD

**Issue by flashios09** [mjsarfatti/nestedSortable#68]
Hi,
Sorry fir my bad english :(
I don't know why toArray return one more object that wrap other objects(it changes the 'left' and 'right' values)
For example if i have 2 'li' it returns for me 3 objects !!
How can i fix it ??

You can see the results in the image below
![nested-sortable-bug](https://f.cloud.github.com/assets/1313482/41935/75a345a2-55f2-11e2-9bbe-be46a6ad1b7e.png)

**Comment by mjsarfatti** [comment]
Hello,
the toArray method is to be used with the "nested set model" (see the left
and right properties), hence it needs a root element with left = 1 and
right = max-right + 1.

It is so by design, if you don't need it just skip the first element :)

2013/1/3 flashios09 notifications@github.com

**Comment by flashios09** [comment]
thanks mjsarfatti :)
i have fixed this problem (see the image below)
i want to combine your plugin(by the way it's a marvelous plugin) with [the tree behavior of  the cakePhp Framework](http://book.cakephp.org/2.0/en/core-libraries/behaviors/tree.html) and i want to detect only the modified objects (not all the objects) after this i will use the jquery ajax method with the sortable update event to change values(parent_id, left, right) in Database
![nested-sortable-fix](https://f.cloud.github.com/assets/1313482/43612/7b3bf94a-568e-11e2-9d5d-c34b7883d5ac.png)

**Comment by josephdpurcell** [comment]
Hey flashios09, I've been following this plugin recently and I'm relying on it heavily for an application of mine. So, first of all, let me say: I'm glad you're using this plugin and contributing!
1. However, I wanted to make sure that you understand mjsarfatti's point: the plugin is designs as a "tree", and all "trees" have a root. Thus, what you claimed as an additional node is false--it is simply the root node. (Research "tree traversal", http://en.wikipedia.org/wiki/Tree_traversal)
2. The tree behavior of the CakePHP framework is very fascinating! That would be a huge time saver! In my case, I just made a JSON object and stored it in a text field.
3. If the application you are working on is open to the public, I would love to take a look at how you've implemented nestedSortable. Likewise, if you are interested, I can show you what I have been working on.

Cheers!

**Comment by flashios09** [comment]
hi joseph,
yes i know that all 'tree' concept must have a root element that contains other elements but with cakePhp tree behavior i don't need this root element.
i explain : 
for adding a parent category just extend the categories array that you send to the view like this : 

``` php
// Category Controller
$d['categories'] = array('Parent Category') + $this->Category->generateTreeList();
```

this will add an index 0 to the select tag

``` html
<options value='0'>Parent Category</options>
```

i want to take a look at your code perhaps we can collaborate together

**Comment by mjsarfatti** [comment]
Hi,
I still think that the best solution would be to throw away the root item
server side, if you don't need it. How would you go with updating the
plugin otherwise?

2013/1/4 flashios09 notifications@github.com
