### ISSUE TITLE
version not up to date?

### ISSUE THREAD

**Issue by alansheep** [mjsarfatti/nestedSortable#69]
the version in the github is not up to date?

functions shown in :http://mjsarfatti.com/sandbox/nestedSortable doesn't work with the library in github. I had to grab the jquery.mjs.nestedSortable.js from the example source code and it is around 4KB different with the one in github.

**Comment by mjsarfatti** [comment]
Hi,
the demo uses the alpha branch, that's why there is a difference in size I
guess

2013/1/9 alantyt notifications@github.com
