### ISSUE TITLE
Conflicts with other plugins that have updated versions of jquery and jquery ui.

### ISSUE THREAD

**Issue by Mikeyheu** [mjsarfatti/nestedSortable#75]
First off this is an amazing plugin. Does exactly what I need it to do. The only issue is that my other plugins in my app that exist on the same page require newer versions of jquery (1.8.3+) and jquery ui to work. When I load jquery 1.7.2 and jquery-ui 1.8.16 the nested sortables work perfectly but then I have issues with the other parts of my app breaking. Specifically, the plugin breaks with newer versions of jquery and jquery-ui when I connect my lists with connectWith option.

What are some possible workarounds on how to approach this? I have heard of noconflict as a possible solution to load 2 diffrent versions of jquery on the same page but I'm not sure if this is a good solution.

Any guidance would be greatly appreciated. Thanks!

**Comment by mjsarfatti** [comment]
Version 2.0 works with jQuery UI 1.10 (only tested in FF and Chrome for the moment, but it should work in IE as well)

**Comment by Mikeyheu** [comment]
Still have the same issues with connectWith. Similar to https://github.com/mjsarfatti/nestedSortable/issues/87
