### ISSUE TITLE
The "protectRoot" option appears to not be functioning.

### ISSUE THREAD

**Issue by Spiderkeg** [mjsarfatti/nestedSortable#79]
When I use the "protectRoot" option, the first sets of &lt;li&gt; can still be moved and nested, made into children.  In using the working example you provided, applying "protectRoot" does not prevent root level items from being nested.

However, in looking at the code, when I apply the "ui-sortable" class to the top parent &lt;ol&gt; the root level items (while still movable around each other) stops nesting and becoming sub-items.

Please advise, is this the correct process, or is there something inherently wrong with the protectRoot option?  Is the "ui-sortable" class a requirement, because this is omitted from the ReadMe file.

**Comment by Spiderkeg** [comment]
After some additional experimentation, my problem does appear to share with https://github.com/mjsarfatti/nestedSortable/issues/38.

The normal jQuery Sortable is linear and right now, if someone were to use "protectRoot" they would still be able to attempt to sort a root item amongst the sub-items.  Perhaps a condition to force the root items to operate linearly might solve the problem.  I'd be happy to have a class I can apply to the root items to force the issue.

My goal: to have the root items sortable <u>only</u> amongst each other, but to have the sub-items under each of the roots items sortable interchangeably.

**Comment by mjsarfatti** [comment]
fixed.
