### ISSUE TITLE
Use HTML5 data attributes instead of id

### ISSUE THREAD

**Issue by webberig** [mjsarfatti/nestedSortable#82]
I have a change request.

When the script serializes the data, it uses the list item's id attribute as the key. It's my oppinion that the id attribute's function is of a more generic nature. HTML 5 allows custom data-\* attributes that serve a specific function, in this case have a "key" for nestedSortable.

Would it be possible to use data attributes instead, and maybe add an option to set the name of this attribute ?

**Comment by mjsarfatti** [comment]
That's how regular sortable works, I wouldn't change that.

**Comment by trsteel88** [comment]
+1 @webberig

**Comment by mjsarfatti** [comment]
Again, the plugin reflects Sortable's default behavior (http://api.jqueryui.com/sortable/#method-serialize). As you can see you can always customize the attr it uses.
