### ISSUE TITLE
New developer needed!

### ISSUE THREAD

**Issue by mjsarfatti** [mjsarfatti/nestedSortable#95]
I'm sorry to say that I am clearly not able to keep up the pace in developing this project anymore. I know how much nestedSortable is important for web applications, and I still can't understand why it's not part of jQuery-UI. I also think the base of the plugin is very strong, and deserves much more attention and involvement. If anybody is willing to take this project, please say so here.

Thank you.

**Comment by nordbyte** [comment]
I am interested to take over this very helpful project. NestedSortable jQuery Plugin saved me a lot of time and it would be a shame if this project die. I'm a web developer for about 10 years now.

**Comment by acrylian** [comment]
It really does not make sense that this isn't part of jQuery UI. We use it for all nested item sorting in the Zenphoto CMS (https://github.com/zenphoto/zenphoto) for some years now and found it superior to all other similar scripts we tried. 

It would be too bad if this would disappear. Sadly I am not that much a jQuery wizard to really help developing (Also a time thing) but I could surely try to do some regular testing.

**Comment by ranjansingh** [comment]
Hey,
Please let me know if any nested sortable demo or code,please share on my emailid-ranjan.eicamca@gmail.com.

Thanks 
Ranjan

**Comment by mjsarfatti** [comment]
Hello nordbyte, sorry for the late reply!
If you whish to continue this project and keep it up to date with jQuery, you can fork this repo (esp. the alpha 2.0 branch) and I will put a link here to you. You can see there are a few open issues here, so you may want to start with those, but it's up to you :)
let me know!

**Comment by ranjansingh** [comment]
Hi mjsarfatti,
I d n't understood alpha 2.0 branch,please let me know.
Kindly tell me how to work over nested sortable.

Thanks

**Comment by gwaldron** [comment]
Thanks for the great tool. I use it extensively so I'll be forking it as well.
https://github.com/gwaldron/nestedSortable

**Comment by mjsarfatti** [comment]
gwaldron, nordbyte hasn't answered yet. if you wish to take on the project, fix the current issues and keep it updated with jQuery let me know and I will link to your fork from the front page!

**Comment by gwaldron** [comment]
Not sure about taking over the project - sounds like nordbyte is probably more qualified than I - but I will do my best to keep it working with jQuery since I'm using it in a (soon to be) production app.

**Comment by FinalAngel** [comment]
I continued working on the **alpha branch** here: https://github.com/FinalAngel/nestedSortable
Will be update regularly as we require it.

**Comment by daedalus-codes** [comment]
@mjsarfatti I'm willing to contribute to the project as well.  This is something that I've been looking for, not to overly simple & manual, yet not too "over the top".  Right now, I'm planing on implementing this in a CMS for several tasks.  I'd be willing to contribute tweaks, features, etc as they come along - though right now it seems to be pretty good as is.  I have too much on my plate to be a project lead, but would like to contribute features/tweaks and be part of the general direction.  

In addition, the jQuery UI Team is considering a "Tree" widget http://wiki.jqueryui.com/w/page/12138128/Tree, which considering it already uses jQuery UI components, I believe it could be a good fit/starting point to bring it in under the jQuery UI umbrella. 

Your thoughts guys?

**Comment by mjsarfatti** [comment]
This should already be part of Sortable... Anyway, a lot is already done,
it just needs a person willing to keep it updated and tested with the new
jQuery releases and to implement the occasional bug fixes.

2013/12/20 Micah Miller notifications@github.com

**Comment by MichaelSp** [comment]
Any decision who is going to continue development? 

BTW: I've setup a rails version [here](https://github.com/MichaelSp/jquery.mjs.nestedSortable-rails)

**Comment by marcucio** [comment]
Looks like there are a bunch of branches out there each with their own fixes, it would be good to agree upon 1 central place to put in fixes:

https://github.com/mjsarfatti/nestedSortable/network

**Comment by MichaelSp** [comment]
I'd vote for @FinalAngel as he put the most effort into his branch. To bad he doesn't want to be the project lead. :/

**Comment by curtd59** [comment]
Someone help me understand what's needed please.
We use nestedSortable in our product.  We can invest a bit in it.
What's the problem here?

---

Curt Doolittle, CEO
Reality By Chanting
Verkhnii Val St, 4,
Kiev, Ukraine 04071
Kiev  -  London  -  Seattle

**Comment by FinalAngel** [comment]
It's probably also related to fixing outstanding issues or adding new features as well as better docs / demos

**Comment by marcucio** [comment]
We have been using the @poscar branch to put in the bug fixes for our app:

https://github.com/poscar/nestedSortable/commits/2.0alpha

I think the hardest part about maintaining it would be responding to all the bug reports, feature requests, and pull requests. I think the maintainer would be mostly a gatekeeper, all the development work is done already.

**Comment by geoidesic** [comment]
Hi Curt,

There are various branches of this plugin by various authors on github.
The problem with this is that there's no single place to get all of the code improvements from. 
If one wanted all the various contributions one would have to checkout from each branch and merge them all in oneself – quite a bit of work.
To fix this, someone needs to take over as the "official" repository administrator.

This would involve:
1. Contacting the original branch owner and offering to do so.
2. Being accepted.
3. Creating a new "canonical" branch of the code.
4. Merging all useful commits into this new branch.
5. Notifying interested parties of the progress so that they can update their own branches and ReadMe files to point to the new canonical branch.
6. Addressing any tickets / bugs etc. 
7. Accepting push future requests and merging these into the canonical branch. 

Kind Regards,
Noel da Costa
www.arc2.co.uk

**Comment by mjsarfatti** [comment]
Hi everybody,
I guess I should say something here :)

As @marcucio said, it's mostly about bug fixing, and keeping up with new jquery releases (eg. the switch to 1.9 broke the plugin at the time). The hardest part is done already. Oh and also, get that 2.0 branch out of alpha (which means simply testing it thoroughly on different browsers, and with the lastest jquery release).

Adding new features, improving the docs etc. are pluses, but not as important as keeping up with the bugs. So once again, is anybody willing to take over? It not like you are gonna maintain a Java CMS... ;)

**Comment by marcancajas** [comment]
I used the plugin as a baseline frontend components for a web application ages ago and planning to use it again soon for something else.

@mjsarfatti sounds like I can do it (Bug fixing, keeping up with new jquery release, testing in general).
I am currently under near-release phase at my work so a bit busy but is there a list of known issues/bugs at the mean time?  I can only see the one regarding the connected draggables.

@mikhey sounds like a good direction, did anyone share or expose this absolutely useful plugin to Jquery yet? 

I do agree that the docs needs a bit of improvement but not particularly important. I think it needs to be a bit more newbie friendly (like explaining how ul li tags works as the draggable things and changing this etc and setting the configurations) and maybe a few more examples of tweaking the styling/css for beginners. List of "stylable" elements if I may say.

I particularly like what they did with their documentation examples in this component: http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/docs/examples.html.

**Comment by marcucio** [comment]
@marcancajas I say go for it, fork the project and we can send you any fixes we put in other branches. If everything looks good we can start directing people to your copy.

**Comment by marcancajas** [comment]
Check it here: https://github.com/marcancajas/nestedSortable
I've done a little bit of altering with the documentation to make it easy to navigate and some plans.

**Comment by marcucio** [comment]
nice, btw we use the library for our app http://manageitapp.com and it works for us on IE (tested on 8 and above), Chrome, Firefox, Safari and with the touchpunch library it also works on Android, iOS, BlackBerry 10, Windows Surface (touch) and Windows Phone. The only changes in the library are what we put in here: https://github.com/poscar/nestedSortable/commits/2.0alpha you might want to pull these changes into your branch.

**Comment by sgpinkus** [comment]
@mjsarfatti cant you just add some collaborators to manage the project from here? I don't think some random fork of this project is going to gain traction. Alternatively you could setup a separate git repo dedicated to nestedSortable.

**Comment by mjsarfatti** [comment]
I'd prefer to choose a fork to be the new official nestedSortable. 
@marcancajas there is the list of known issues in the documentation, but mostly it's the open issues here on github. So if you agree I would place a link to your fork as the new maintained nestedSortable?

**Comment by marcancajas** [comment]
@mjsarfatti yup that sounds great, although Sam does make a good point, I guess If I need help or someone else wants to help out they can join my fork as collaborators. I'm planning to create a web page that host examples etc.. as soon as I get everything clear and up to date.
@marcucio Great! I pulled the changes to my alpha2.0 branch from that. That's one thing out of the way. I'll get the master branch updated with everyone's stuff and sorted out soon and its documentation after I test it with jQuery-ui 1.10.4 (edited).

so If you guys have added a feature or something just send me a message saying 
"What" 
"Why" 
"How" 
"Where"
 I'll try to update my fork with your changes/additions so we can have it all collected. :+1:

**Comment by marcucio** [comment]
@marcancajas cool, just so you know we are using jquery 1.11.0 and jquery-ui 1.10.3 and it works well on our project. You might want to test with the latest jquery instead of 1.9

**Comment by marcancajas** [comment]
Oh right. That leaves me with only jquery-ui 1.10.4. Awesome

**Comment by ashishnaicker** [comment]
I'd like to fork off this project to create an extension for Yii.

**Comment by marcancajas** [comment]
Hi Ashish,

Please go ahead and let me know how its working out. I am an avid yii developer as well so this is interesting for me and maybe I can help.

**Comment by ilikenwf** [comment]
I don't really want to be the maintainer/developer but I have merged in some of the pull requests to my own repo... I tried merging some of the other updates and changes from the other people in the network with good looking changes but they caused problems that I didn't have time to fix.

https://github.com/ilikenwf/nestedSortable

**Comment by ilikenwf** [comment]
Ok...well, I've merged some of the pull requests and added the example, with updates to my repo linked above as well.

**Comment by ilikenwf** [comment]
I suppose I can take over as maintainer as long as the community reviews everything and provides pull requests. Since the version I have is stable and working for what I need, I'm not sure how much I'll be doing in terms of additions to the project.

**Comment by ghost** [comment]
Any recent status on this?
- has jqueryui sortable been updated, so it can be used with nested sorting using connectedWith?
- if not, I see several people saying they can continue maintenance, can one be chosen?, so there can be one single concerted effort, rather than a bunch of forks forcing everyone to continue forking on their own and resulting in much uncertainty and redundant work.

**Comment by ghost** [comment]
@ilikenwf sounds great that you have a stable version, and it's great if it does the single job it is supposed to, and it is maintained for that purpose. With that purpose being defined, it's good enough I say. How about we turn that into the master branch, what say you @marcancajas ?

**Comment by marcancajas** [comment]
Hey guys,

Really busy sorry and yeah by all means, as for the connect list compatibility I would based its compatibility on the jquery ui version but I don't see why not, its essentially the same elements as the connect list demo but with this element would have the nestedSortable functionality. I've done something before with different functionalities all combined together XD it was messy but man it worked.

Also really happy to see everyone getting involved and maintaining this cause this is such a useful UI component for any website/webapp. 
Cheers :)

**Comment by mjsarfatti** [comment]
Sorry guys, long time no see.
So let's wait for a confirmation by @ilikenwf to take over, maybe he could have @marcancajas as a collaborator if both want to work on the project. I will then link the new official repo from the README.

**Comment by ilikenwf** [comment]
I can, if you guys would like. I would also be fine with having multiple maintainers - why not just approve all of the above as well as myself? I can then pull request my changes, and they theirs.

My demo, by the way:  http://ilikenwf.github.io/example.html

CSS needs some cleanup, but otherwise works well IMO.

**Comment by mjsarfatti** [comment]
@ilikenwf I linked your fork from the README :)
Thank you for taking care of this!
